@startuml
'https://plantuml.com/class-diagram
!theme mono 
Turno --- Paciente
Turno --- Medico

Medico --- Especialidad
Medico --- HoraLaboral



Paciente --- Usuario
Medico --- Usuario
Usuario --- TipoUsuario

class Usuario{
-int id
-String name
-String email
-String password
-TipoUsuario tipoUsuario
}
class Turno{
    -int id
    -Date fecha
    -String estado
    -String observacion
    -Medico medico
    -Paciente paciente
  /'  +int getId()
    +void setId(int id)
    +String getFecha()
    +void setFecha(String fecha)
    +String getHora()
    +void setHora(String hora)
    +String getEstado()
    +void setEstado(String estado)
    +String getDescripcion()
    +void setDescripcion(String descripcion)
    +Medico getMedico()
    +void setMedico(Medico medico)
    +Paciente getPaciente()
    +void setPaciente(Paciente paciente)'/
    }

class Persona{
    -String nombre
    -int edad
    -String sexo
    -String direccion
    -String telefono
    -String correo
    +String getNombre()
    +void setNombre(String nombre)
    +int getEdad()
    +void setEdad(int edad)
}


class Paciente extends Persona{
    -int idPrepaga
    +String getNombre()
    +void setNombre(String nombre)
    +int getEdad()
    +void setEdad(int edad)
    +String getPadecimiento()
    +void setPadecimiento(String padecimiento)
}
class Medico extends Persona{
    -int matricula
    -list<Especialidad> especialidad
    +String getNombre()
    +void setNombre(String nombre)
    +int getEdad()
    +void setEdad(int edad)
    +String getEspecialidad()
    +void setEspecialidad(String especialidad)
}
class Especialidad{
    -String nombre
    -String descripcion
    +String getNombre()
    +void setNombre(String nombre)
    +String getDescripcion()
    +void setDescripcion(String descripcion)
}
class HoraLaboral{
    -Date horaEntrada
    -Date horaSalida
    -String Dias
    -String estado
    +String getHora()
    +void setHora(String hora)
    +String getEstado()
    +void setEstado(String estado)
}
class TipoUsuario{
    -int Id
    -String Tipo
    +Bool Estado
    +void setNombre(String nombre)
    +String getDescripcion()
    +void setDescripcion(String descripcion)
}

@enduml