//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clínica_WebApp
{


    public partial class Dash
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Clínica_WebApp.SiteMaster Master
        {
            get
            {
                return ((Clínica_WebApp.SiteMaster)(base.Master));
            }
        }
    }
}
