//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_WebApp.Admin
{


    public partial class prue
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Clinica_WebApp.Admin.lala Master
        {
            get
            {
                return ((Clinica_WebApp.Admin.lala)(base.Master));
            }
        }
    }
}
